plugins:
  - babel
  - jest
env:
  node: true
  jest: true
parser: babel-eslint
extends:
  - 'airbnb-typescript/base'
  - 'plugin:jest/recommended'
rules:
  no-console: 0
# test-specific configuration
overrides:
    rules:
      promise/always-return: off
      jest/expect-expect:
        - warn
        - assertFunctionNames:
            - "expect*"
